version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/chatter/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    environment:
      - BASE_HOST=http://
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatter.rule=Host(`chatter.localhost`)"
      - "traefik.http.routers.chatter.entrypoints=web"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - chatter

  cassandra:
    image: cassandra:latest
    hostname: cassandra-server
    ports:
      - 9042:9042
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      default:

volumes:
  cassandra_data:

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik
