version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/chatter/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    environment:
      HOST: 0.0.0.0
      PORT: 80
      VERIFICATION_URL: http://uacl/authorize
      NOTIFICATION_URL: http://notif/internal_notification
      EMOTIVES_URL: http://localhost/
      NOTIFICATION_AUTH: qutSecret
      ALLOWED_ORIGINS: http://localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatter.rule=Host(`chatter.localhost`)"
      - "traefik.http.routers.chatter.entrypoints=web"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - chatter

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik
