version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/chatter/Dockerfile.prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    environment:
      - BASE_HOST=http://
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatter.rule=Host(`chatter.emotives.net`)"
      - "traefik.http.routers.chatter.tls=true"
      - "traefik.http.routers.chatter.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - chatter

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik