version: '3'

services:
  api:
    image: ghcr.io/tombowyerresearchproject/chatter_api:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    environment:
      HOST: 0.0.0.0
      PORT: 80
      VERIFICATION_URL: http://uacl/authorize
      NOTIFICATION_URL: http://notif/internal_notification
      EMOTIVES_URL: https://emotives.net/
      NOTIFICATION_AUTH: qutSecret
    logging:
      driver: syslog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatter.rule=Host(`chatter.emotives.net`)"
      - "traefik.http.routers.chatter.tls=true"
      - "traefik.http.routers.chatter.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - chatter

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik