name: Merged items

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  build-and-push-image:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Build image
        run: ./scripts/build.sh
      - name: Log in and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u imthetom --password-stdin
          docker push ghcr.io/tombowyerresearchproject/chatter_api:latest
      - name: Connect and deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          host: 162.0.216.160
          username: root
          password: Github123
          port: 22
          script: |
            echo $GITHUB_TOKEN | docker login ghcr.io -u imthetom --password-stdin
            docker pull ghcr.io/tombowyerresearchproject/chatter_api:latest
            rm -R chatter
            git clone git@github.com:TomBowyerResearchProject/chatter.git
            cd chatter
            ./scripts/start.sh prod